language: node_js

node_js: stable

cache:
  yarn: true

install: yarn

script:
  - yarn run generate
  - cp README.md dist/README.md


deploy:
  provider: pages
  skip-cleanup: true
  github-token: $BLOG_TOKEN
  local-dir: dist
  target-branch: master
  verbose: true
  on:
    branch: vue
