# 因主题配置文件 _config.yml 中有有隐私 key ，故不上传 themes/name/_config.yml 文件。

# 在没有 theme/name/_config.yml 的情况下，无法正常编译静态文件。故暂时弃用 CI 部署

languaga: node_js

sudo: required

node_js: stable

cache:
  yarn: true

install:
  - yarn

before_script:
  - chmod +x ./deploy.sh

script: 
  - sh deploy.sh 'deploy site:by CI'

branch:
  only:
    - dev
