version: 2
jobs:
  build:
    branches:
      ignore:
        - master

    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    environment:
      - SOURCE_BRANCH: vue
      - TARGET_BRANCH: master
      - USERNAME: Bowen
      - USEREMAIL: mr_lbw@outlook.com

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: Install dependencies
          command: yarn

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Test generating process
          command: yarn generate

      - deploy:
          name: Deploy site
          command: |
            if [ $CIRCLE_BRANCH == $SOURCE_BRANCH ]; then
              git config --global user.email $USEREMAIL
              git config --global user.name $USERNAME

              git clone $CIRCLE_REPOSITORY_URL out

              cd out
              # git checkout $TARGET_BRANCH
              # This op will create a branch named 'master'
              git checkout --orphan $TARGET_BRANCH
              git rm -rf .
              cd ..

              yarn generate

              cp -a dist/. out/.

              mkdir -p out/.circleci && cp -a .circleci/. out/.circleci/.
              cd out

              git add -A
              git commit -m "docs: Deployed by CircleCI - ${CIRCLE_SHA1}" --allow-empty

              git push origin $TARGET_BRANCH
            fi
